name: Test Actions

on:
  workflow_dispatch: # запуск только вручную

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "✅ GitHub Actions работает!"
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Pack NuGet
        run: |
          VER="0.1.${GITHUB_RUN_NUMBER}"
          dotnet pack Package\XrayCore.MTProto.Proto.csproj -c Release -p:PackageVersion=$VER